### ISSUE TITLE
How did you make this?

### ISSUE THREAD

**Issue by JBYT27** [RayhanADev/Pride-Furrets#1]
Hiya @RayhanADev, 

Quick question, did you paint or draw those pics?
Or did you just fill it in with an art editor?
Thanks :)

**Comment by RayhanADev** [comment]
I used my profile pic (which is a photoshop of a basic Furret I found online) and then used fill buckets to color the bands with a template. It's a lot of Photoshop and filters :D.

**Comment by JBYT27** [comment]
Ah, ok. Very kewl!
Thanks!

**Comment by RayhanADev** [comment]
No problem ;D.
